// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP3oJJo-uC1feeWKnCWA7H-_hn8O97YKE',
    appId: '1:358862481829:web:6004a44a2ef71c8c5ca04c',
    messagingSenderId: '358862481829',
    projectId: 'e-learning-cee59',
    authDomain: 'e-learning-cee59.firebaseapp.com',
    storageBucket: 'e-learning-cee59.appspot.com',
    measurementId: 'G-0PQEDVZEYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvs2KV9CDb6jZLKjcaojbiji6OERiD-p4',
    appId: '1:358862481829:android:d879422fad40b9165ca04c',
    messagingSenderId: '358862481829',
    projectId: 'e-learning-cee59',
    storageBucket: 'e-learning-cee59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANtrs06Um_bvxGMHg29eVh2P8c-xVllqE',
    appId: '1:358862481829:ios:c351cfe7d1356c825ca04c',
    messagingSenderId: '358862481829',
    projectId: 'e-learning-cee59',
    storageBucket: 'e-learning-cee59.appspot.com',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANtrs06Um_bvxGMHg29eVh2P8c-xVllqE',
    appId: '1:358862481829:ios:c351cfe7d1356c825ca04c',
    messagingSenderId: '358862481829',
    projectId: 'e-learning-cee59',
    storageBucket: 'e-learning-cee59.appspot.com',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP3oJJo-uC1feeWKnCWA7H-_hn8O97YKE',
    appId: '1:358862481829:web:29fea36278b472285ca04c',
    messagingSenderId: '358862481829',
    projectId: 'e-learning-cee59',
    authDomain: 'e-learning-cee59.firebaseapp.com',
    storageBucket: 'e-learning-cee59.appspot.com',
    measurementId: 'G-PD97QRDD4E',
  );
}
